version: '3'
services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    container_name: nextjs-contact
    volumes:
      - ./:/usr/src/app
    command: 'yarn dev'
